name: Write file

on: [push]

jobs:
  write_file:
    runs-on: ubuntu-latest

    steps:
      - name: Write file
        run: |
          printf "\
          ZBAY_UPLOAD_STORE_FILE=zbaymobile.keystore\n\
          ZBAY_UPLOAD_KEY_ALIAS=${{ SECRETS.GOOGLE_KEYSTORE_ALIAS }}
          ZBAY_UPLOAD_STORE_PASSWORD=${{ SECRETS.GOOGLE_KEYSTORE_PASSWORD }}\n\
          ZBAY_UPLOAD_KEY_PASSWORD=${{ SECRETS.GOOGLE_KEYSTORE_PASSWORD }}\
          " > $HOME/file.txt

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: file.txt
          path: $HOME/file.txt
          retention-days: 1
